### ISSUE TITLE
Modalを表示させる

### ISSUE THREAD

**Issue by b1017173** [b1017173/Hometoku#2]
**作ろうとしている機能の詳細**
ゴール：Slack内のショートカットでアプリを選択することで，Modalを表示する．
プロセス： 
1. Slack内にアプリを起動させるアクションパーツを配置する
2. アクションの起動をハンドリング(検知)する
3. アクションが起動された際にmodal.json(issue: #1 )をSlackに送信
4. 整形されたModalがSlackで表示される

**完成の定義**
バグの精査(入り込みそうなバグ)： 
1. 接続ができない
2. アクションボタンを連打するとバグる
3. モーダルの表示がバグってる

**見積もり**
2 d / 人

**その他**
***作業ブランチ***
main - develop - issue02
***特筆事項***

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。
3. 作業ブランチを切って，ブランチ名はイシュー名にする．
    ex)issue23 , issue33 とか

**Comment by b1017173** [comment]
手詰まりなので，知見共有
# やりたいこと
ショートカットアクションをリスナーする．ためにアプリと接続する．

# 接続するためには
- [x] アプリの開発環境を用意する
- [x] ngrok環境を用意する
- [x] ngrokからローカルに繋ぐパブリックなURLを取得する
- [x] アプリの設定ページからEvent Subscriptionの設定を開く
- [x] アプリを動かした状態でURLのとこに`ngrokで取得したurl/slack/events`で登録する
- [ ] 成功すれば接続完了

# この作業の目的
最初に一回だけ認証を行なってサーバーが生きているかをチェックする機能．
自動で適切な返答をするようにBoltには組み込まれている(はず)．

# エラー状況
## アプリ設定画面のエラー
> Request URL Your URL didn't respond.
> https://16fafc2344ab.ngrok.io/slack/events
> We’ll send HTTP POST requests to this URL when events occur. As soon as you enter a URL, we’ll send a request with a  challenge parameter, and your endpoint must respond with the challenge value. Learn more.
## 実行画面のエラー
> Exception occurred during processing of request from ('127.0.0.1', 57175)
Traceback (most recent call last):
  File "/Users/micad/.pyenv/versions/3.9.4/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/micad/.pyenv/versions/3.9.4/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/Users/micad/.pyenv/versions/3.9.4/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/micad/.pyenv/versions/3.9.4/lib/python3.9/http/server.py", line 653, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/micad/.pyenv/versions/3.9.4/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/micad/.pyenv/versions/3.9.4/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/Users/micad/.pyenv/versions/3.9.4/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/Users/micad/Develop/PythonProjects/Hometoku/.venv/lib/python3.9/site-packages/slack_bolt/app/app.py", line 1342, in do_POST
    bolt_resp: BoltResponse = _bolt_app.dispatch(bolt_req)
  File "/Users/micad/Develop/PythonProjects/Hometoku/.venv/lib/python3.9/site-packages/slack_bolt/app/app.py", line 455, in dispatch
    resp = middleware.process(req=req, resp=resp, next=middleware_next)
  File "/Users/micad/Develop/PythonProjects/Hometoku/.venv/lib/python3.9/site-packages/slack_bolt/middleware/request_verification/request_verification.py", line 37, in process
    if self.verifier.is_valid(body, timestamp, signature):
  File "/Users/micad/Develop/PythonProjects/Hometoku/.venv/lib/python3.9/site-packages/slack_sdk/signature/__init__.py", line 53, in is_valid
    calculated_signature = self.generate_signature(timestamp=timestamp, body=body)
  File "/Users/micad/Develop/PythonProjects/Hometoku/.venv/lib/python3.9/site-packages/slack_sdk/signature/__init__.py", line 70, in generate_signature
    encoded_secret = str.encode(self.signing_secret)
TypeError: descriptor 'encode' for 'str' objects doesn't apply to a 'NoneType' object

一応ngrok側でリクエストはポストできている
> POST /slack/event

# やったこと
1. 起動順番の変更
2. port番号の変更
3. Node.jsを用いた接続(Boltを使ってない上にjsだったので断念)

# 参考サイト
https://api.slack.com/start/building/bolt-python
https://slack.dev/bolt-python/ja-jp/tutorial/getting-started
https://api.slack.com/tutorials/tunneling-with-ngrok

**Comment by b1017173** [comment]
# 解　決　し　ま　し　た

解決手法　→　再　起　動　☆

**Comment by b1017173** [comment]
## 正しいテスト環境の作り方
1. mian.pyを動かす
2. ngrokを動かす
3. Event Subscriptionで接続テスト
4. アプリ設定の更新
5. リインストール
6. 操作
